# Generated by Django 3.2.5 on 2021-07-14 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=84)),
                ('description', models.TextField(null=True)),
                ('publishDate', models.DateField(null=True)),
                ('pageCount', models.IntegerField(null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mylibrary.author')),
            ],
        ),
    ]
